### ISSUE TITLE
need features discussion

### ISSUE THREAD

**Issue by endepointe** [SecurityLogMiner/log-collection-backend#6]
Lets add a discussion to help us work towards what features we need to add. A few that John and I discussed:

- reading of appended data to log files (in-progress)
- detect custom/ ambiguous log formats when given field names within a config file
- handle authentication
- database setup
-  ... anything else

**Comment by khuynh2002** [comment]
- export and import functionality
- load balancing mechanism
- capture status level of an event log and evaluate against alert conditions
- convert parsed log data information into a common file type (format TBD) for searching and summary report use

**Comment by endepointe** [comment]
As far as I am aware, we arent building a SIEM. What we are doing is taking logs generated from an endpoint and sending it to a central server. I like the feature ideas as an option down the road. 

Handling the core requirements of ensuring the up status of the log collection service should be the priority. Features such as how we define and handle the incoming data, the encryption, authentication, and monitoring during data transfer have a greater importance at this stage. 

The system design outlines the components we will need to just take log data from source to destination.

This weekend, and going into next week, I would like to have data generated from source be visible at the destination, which would be the aws server that is currently running (see discord)

**Comment by Jicxer** [comment]
Closing Issue
