### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by Jicxer** [SecurityLogMiner/log-collection-backend#9]
Develop a command line interface for the user for accessibility. We would want the command line to prompt the user for specific input formatting; and offer alternative informational commands such as "--help".

If there are additional suggestions for command line functionality please provide feedback.

- [ ] (https://github.com/SecurityLogMiner/log-collection-client/issues/17)
- [ ] (https://github.com/SecurityLogMiner/log-collection-client/issues/18)

**Comment by endepointe** [comment]
Arbitrarily changing the server address and port from the command line seems like a bad idea now that I think about it. it would be better to have the user /sys admin add the destination data in a config file. This is currently being worked on here: https://github.com/SecurityLogMiner/log-collection-client/issues/17

**Comment by Jicxer** [comment]
Sounsd good. I'll edit the issue to reflect these changes.
